In [1]:
import numpy as np

1. Dimenions of Arrays
 

In [2]:
#Creating a 1D arrays (or) Normal Array creation 
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))  # type() = used to check the data type of an array

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
#Creating a 2D arrays
arr1 = np.array([[1, 2, 3],[4, 5, 6]])    #2 rows , 3 coloumns
print(arr1)
print("dimension = ",arr1.ndim)  # ndim = used check the dimensions of the array

[[1 2 3]
 [4 5 6]]
dimension =  2


In [4]:
#Creating a 3D arrays
arr2 = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])   # 3 rows , 3 coloumns
print(arr2)
print("dimension = ",arr2.ndim)  # ndim = used check the dimensions of the array

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension =  3


2. Array Creation (np.zeros())


In [5]:
# np.Zeros()
# Syntax = var = np.zeros(shape , datatype)
arr = np.zeros(5,)  # creats total 5 zeros with default datatype as 'float'

In [6]:
arr = np.zeros(5, dtype = int)  # creats total 5 zeros with a datatype as 'int' by passing Explicitly 
print(arr)

[0 0 0 0 0]


In [7]:
# creats an 3 rows , 3 coloumns with a value zeros as datatype 'int'
arr = np.zeros((3, 3), dtype = int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
# Create a 3D array of zeros (2 blocks, 3 rows, 4 cols)
arr = np.zeros((2, 3, 4), dtype = int)
print(arr) 

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [9]:
# Replacing the exixting elements using the index values 
arr[0][2] = 5   # [1]row , [5]coloumn value as 5 ,here it using the 2 blocks of matrix 
print(arr)

[[[0 0 0 0]
  [0 0 0 0]
  [5 5 5 5]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [10]:
arr[1, 2] = 7  # row 1, col 2 using the existing variable 'arr'
print(arr)

[[[0 0 0 0]
  [0 0 0 0]
  [5 5 5 5]]

 [[0 0 0 0]
  [0 0 0 0]
  [7 7 7 7]]]


3. Array Creation (np.ones)

In [11]:
# Creats the all array values as '1'
arr_1 = np.ones(5,)   # it also gives the datatype as 'float' by default
print(arr_1)
print(arr_1.dtype)

[1. 1. 1. 1. 1.]
float64


In [12]:
arr_1 = np.ones(5, dtype = 'int')   # passing the datatype by Explicitly as 'int'
print(arr_1)

[1 1 1 1 1]


In [13]:
arr_1 = np.ones(((3, 3)), dtype = int)  # 3 rows , 3 coloumns of 2D array
print(arr_1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
# Difference Between type() and dtype() with syntax
# syntax : print(type(var))  --it classifys the object or class of array
# syntax : print(arr.dtype)  --it identifies the datatype of array

In [15]:
# Replacing the existing elements using the index values
arr_1[1, 1] = 4
print(arr_1)

[[1 1 1]
 [1 4 1]
 [1 1 1]]


In [16]:
arr_2 = np.ones((2, 3, 4), dtype = 'int') # 2 blocks , 3 rows , 4 coloumns of 2D array
print(arr_2)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


4. Array Creation (np.full())

In [17]:
#Creating the 1D arrays with a specific values based on the shapes
#syntax : var = np.fill(shape, value) 
arr2 = np.full(4, 3.14)
print(arr2)

[3.14 3.14 3.14 3.14]


In [18]:
#creating 3x3 matrix with an specific value 3.14
arr2 = np.full((3, 3), 3.14)
print(arr2)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]


In [19]:
# Replacing the existing elements using the index values 
arr2[2, 1] = 9
print(arr2)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 9.   3.14]]


In [20]:
#3D array 
arr = np.full((2, 3, 4), 6)
print(arr.shape) 
print(arr)

(2, 3, 4)
[[[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]]


In [21]:
#syntax : var = var.astype(datatype) or var.astype('i') , 'i' = int
arr2[1,2] = 7
arr2 = arr2.astype('int')   # convertion of float into int using astype() function 
print(arr2)

[[3 3 3]
 [3 3 7]
 [3 9 3]]


5. Array Creation (np.arange())

In [22]:
# Creats an array within the given range 
#Synatx : var = np.arange(start, end)
arr_3 = np.arange(0,10)
print(arr_3)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
# Creats an even arrays within the given range with step '2'
#syntax = var = np.arange(start : stop : step)
arr = np.arange(0, 21, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [24]:
# Countdown from 10 to 1 using Negetive indexing as step (-1)
arr = np.arange(10, 0, -1)
print(arr)  

[10  9  8  7  6  5  4  3  2  1]


In [25]:
# Multiples of 5 from 0 to 100
arr = np.arange(0, 101, 5)
print(arr)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


In [26]:
# Odd numbers from 1 to 19
arr = np.arange(1, 20, 2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


In [27]:
# Reshape into 3x3 matrix -->it only occures when it depends on the total numbers to given matrix only
arr = np.arange(1, 10).reshape((3, 3))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
# Floating Point Values 
arr = np.arange(1.0, 9.0)
print(arr)
# In floating point values are same as 1.0 from given 1. both are same

[1. 2. 3. 4. 5. 6. 7. 8.]


6. Array Creation (np.linespace())

In [29]:
# Creats a array of evenly spaced values between a given 'start' and 'stop' value, based on the 'number' of elements required.
#syntx : var = np.linspace(start, stop, num)
arr = np.linspace(0, 5, 4)
print(arr)
# In linspace the 'start' and 'stop' numbers both are considered & the output always in 'Float point' by default
# Step is workes on the Formula "step = stop - start / num -1"

[0.         1.66666667 3.33333333 5.        ]


In [30]:
arr = np.linspace(0, 6, 5)
# If we want a array in the type of 'int' us astype() function 
print(arr.astype(int))
# All the problems in linspace are works on the step formula which gives an equal spaces 

[0 1 3 4 6]


In [31]:
# Create array with No End Point
arr = np.linspace(1, 9, 5, endpoint = False)
print(arr)
# Passing the Arguments 'endpoint = False' which removes the last element

[1.  2.6 4.2 5.8 7.4]


In [32]:
# Creats array with End point Normal Linspace
arr = np.linspace(2, 8, 5, endpoint = True)
print(arr)
# Passing the arguments 'endpoint = False' or Without passing it , gives default

[2.  3.5 5.  6.5 8. ]


In [33]:
# Creats an array and gives the step size were passing the argument 'retstep = True'
arr = np.linspace(2, 8, 5, retstep = True)
print(arr)
# endpoint controls whether last element is included, and retstep only returns the step size

(array([2. , 3.5, 5. , 6.5, 8. ]), np.float64(1.5))


7. Array Creation (np.random.random())

In [34]:
# Creats an Array of Random Numbers Between the 0 & 1
arr = np.random.random()
print(arr)
# Creats only one Value without passing any shape value with a DataType as 'Float' with defalut type

0.9548799465488302


In [35]:
# Creats a 1D Array of Random Numbers between 0 & 1
arr = np.random.random(1)
print(arr)
print(arr.ndim)  # Checks the Dimension of Array

[0.18557351]
1


In [36]:
# Creats a 2D Array 
arr = np.random.random((2, 2))
print(arr)
print("Dimension :", arr.ndim)

[[0.49880298 0.80005611]
 [0.38686605 0.92142083]]
Dimension : 2


In [37]:
# Creats a 3D Array (Blocks : Rows : Coloumns)
arr = np.random.random((2, 3, 3))
print(arr)
print("Dimension :",arr.ndim)

[[[0.04326273 0.23207869 0.28143234]
  [0.65400454 0.68804894 0.12415257]
  [0.23118281 0.62539216 0.99296696]]

 [[0.45696687 0.76325718 0.66557154]
  [0.43473721 0.84062447 0.33094769]
  [0.6799862  0.28139989 0.05676915]]]
Dimension : 3


In [38]:
# Range Convertion from 0 to 10
# Streched from 0 to 1 - 0 to 10 By multiplying 10
arr = np.random.random(5) * 10
print(arr)

[4.63319259e+00 3.17514017e-03 2.33175713e-01 9.69367085e+00
 4.59144320e+00]


In [39]:
# random * (max - min) + min
arr = np.random.random(5) * (15 - 5) + 5
print(arr)

[ 6.68523751  9.87994639  5.73144067 13.2029445   6.63717825]


8. Array Creation (np.random.normal())

In [40]:
# Generate random numbers following a Normal Distribution (also called Gaussian distribution or bell curve).
# Not completely random, but cluster around a central value.
# Loc = Median , Scale = Standard Deviation , Size = Numbers we want (shape)
arr = np.random.normal(loc=0, scale=1, size=5)
print(arr)
# Here the loc is 0 and the scale gives the values around 1 witha size 5

[-1.15677577 -1.06045239  0.80433889  0.51652617  0.31683571]


In [41]:
# All some values are far from the mean value 40
arr = np.random.normal(loc = 40, scale = 20, size = 5)
print(arr)

[ 13.95423583  15.34076039  43.3140987  -18.74729633  30.97719058]


In [42]:
# Small spread → values stay close to mean
# Large spread → values go far from mean
# If we want to convert the type from float to int use 'astype()' function
arr = np.random.normal(loc=50, scale=10, size=5).astype(int)
print(arr)

[28 46 47 63 68]


In [43]:
# Numbers are around 0
# Some positive, some negative
arr = np.random.normal(loc=0, scale=1, size=5)
print(arr)

[ 1.03036125  0.05076311  0.26315974  1.16151281 -1.67716219]


In [44]:
# 2D Array
#syntax : var = np.random.normal(Mean, Spread, (rows, coloumns)) ; o - mean , 1 - spread values around 1
arr = np.random.normal(0, 1, (2, 3))
print(arr)

[[ 0.03306397  0.37481157 -1.48783917]
 [-0.21468317  0.94584361 -2.42062657]]


In [45]:
# mean - 50 , spread - 5 , values around 50
arr = np.random.normal(50, 5, (3, 2))
print(arr)

[[50.60301737 48.06258055]
 [39.32686889 47.12763831]
 [45.66330619 57.96342903]]


In [46]:
# mean - 50 , spread - 5 , values are Far far 50
arr = np.random.normal(50, 15, (3, 2))
print(arr)

[[37.98074844 40.85657807]
 [80.54788328 54.82878095]
 [59.90572722 61.35298265]]


9. Array Creation (np.random.randint())

In [47]:
# Creats a Random Integers 
# Synatx  = np.random.randint(low, high, size)
arr = np.random.randint(1, 10, 10)
print(arr)
# Low - Value included , High - Value Excluded

[4 8 1 1 9 9 2 2 6 1]


In [48]:
# 2D Array
arr = np.random.randint(1, 20, (2, 2))
print(arr)

[[11  7]
 [13 14]]


In [49]:
# 3D Array
# syntax = var = np.random.randint(start, stop, (block, rows, columns))
arr = np.random.randint(1, 50, (2, 3, 4))
print(arr)

[[[21 33 12  9]
  [47 48 23  7]
  [ 1 31 15  9]]

 [[ 2 37 43 10]
  [44 44 46 39]
  [25  5 46 34]]]


In [50]:
# Even Numbers only
arr = np.random.randint(0, 10, 5) * 2
print(arr)

[ 8 18  0 14 12]


In [51]:
# Only Binary Numbers
arr = np.random.randint(0, 2, 5)
print(arr)

[0 0 0 1 0]


10. Array Creation (np.eye())

In [52]:
# Creats a Array with an Identity Matrix with Diagonal value as 1
# syntax = np.eye(N, M=None, k=0) where N = rows , M = coloumns , k = diagonals
arr = np.eye(2).astype(int)
print(arr)
# Datatype is 'float point' as default
# Convert type using 'astype()' function


[[1 0]
 [0 1]]


In [53]:
# we can change the diagonal posistion (index) also using 'k' value 
arr = np.eye(4, k = 1)
print(arr)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [54]:
# Diagonal is form backward using the 'k' value (Negetive indexing)
arr = np.eye(4, k=-1)
print(arr)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


11. Array Creation (np.empty())

In [55]:
# Creates an array without initializing values
# It does NOT fill with zeros
arr = np.empty(1)
print(arr)

[0.]


In [56]:
# It just allocates memory
# Values inside are random garbage (whatever was already in memory)
arr = np.empty(2, dtype = int)
print(arr)

[     4294967296 281474976710912]


In [57]:
# Create an empty array of size 4 and assign values [10, 20, 30, 40]
arr = np.empty(4, dtype = int)
arr[:] = [10, 20, 30, 40,]
print(arr)

[10 20 30 40]


12. Array Creation (np.random.rand())

In [58]:
# Creats an Random Array between 0 and 1 and without passing the 'tuple'
# Default Type as Float
# 1D Array
arr = np.random.rand(3)
print(arr)

[0.2446728  0.01465545 0.09682927]


In [59]:
# 2D Array
# In this we not passing the tuple value for the 2D array , if we passed tuple the TypeError is raised
arr = np.random.rand(2,2)
print(arr)

[[0.36790905 0.0700511 ]
 [0.35533284 0.90990986]]


In [60]:
# 3D Array without passing any tuple 
# Converting the type into int using the astype 
arr = np.random.rand(2, 3, 2).astype(int)
print(arr)

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


13. Array Creation (np.random.seed())

In [ ]:
# seed is a starting number you give to the random number generator. Array Reproducability
# Once you set it, NumPy produces the same random numbers every single time. Without a seed, results change every run.
arr = np.random.seed(0)
print(np.random.random(2))

arr = np.random.seed(0)
print(np.random.random(2))

# After running the same code using np.random.seed it gives seame random numbers

[0.5488135  0.71518937]
[0.5488135  0.71518937]


In [ ]:
# When the seed value changes the another function values are also changed.
np.random.seed(4)
print(np.random.rand(4))

# np.random.seed funtion which controls ALL random functions in NumPy.

np.random.seed(4)
print(np.random.random(4))
# When the seed value is same the another function gives the same value unless any attribute is used. 

[0.96702984 0.54723225 0.97268436 0.71481599]
[0.96702984 0.54723225 0.97268436 0.71481599]
