In [1]:
import numpy as np

1. Creation of Arrays And Dimenions of Arrays
 

In [2]:
#Creating a 1D arrays (or) Normal Array creation 
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))  # type() = used to check the data type of an array

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
#Creating a 2D arrays
arr1 = np.array([[1, 2, 3],[4, 5, 6]])    #2 rows , 3 coloumns
print(arr1)
print("dimension = ",arr1.ndim)  # ndim = used check the dimensions of the array

[[1 2 3]
 [4 5 6]]
dimension =  2


In [4]:
#Creating a 3D arrays
arr2 = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])   # 3 rows , 3 coloumns
print(arr2)
print("dimension = ",arr2.ndim)  # ndim = used check the dimensions of the array

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension =  3
