In [1]:
import numpy as np

1. Dimenions of Arrays
 

In [2]:
#Creating a 1D arrays (or) Normal Array creation 
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))  # type() = used to check the data type of an array

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
#Creating a 2D arrays
arr1 = np.array([[1, 2, 3],[4, 5, 6]])    #2 rows , 3 coloumns
print(arr1)
print("dimension = ",arr1.ndim)  # ndim = used check the dimensions of the array

[[1 2 3]
 [4 5 6]]
dimension =  2


In [4]:
#Creating a 3D arrays
arr2 = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])   # 3 rows , 3 coloumns
print(arr2)
print("dimension = ",arr2.ndim)  # ndim = used check the dimensions of the array

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension =  3


2. Array Creation (np.zeros())


In [ ]:
# np.Zeros()
# Syntax = var = np.zeros(shape , datatype)
arr = np.zeros(5,)  # creats total 5 zeros with default datatype as 'float'

[0. 0. 0. 0. 0.]


In [ ]:
arr = np.zeros(5, dtype = int)  # creats total 5 zeros with a datatype as 'int' by passing Explicitly 
print(arr)

[0 0 0 0 0]


In [ ]:
# creats an 3 rows , 3 coloumns with a value zeros as datatype 'int'
arr = np.zeros((3, 3), dtype = int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [11]:
# Create a 3D array of zeros (2 blocks, 3 rows, 4 cols)
arr = np.zeros((2, 3, 4), dtype = int)
print(arr) 

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
# Replacing the exixting elements using the index values 
arr[0][2] = 5   # [1]row , [5]coloumn value as 5 ,here it using the 2 blocks of matrix 
print(arr)

[[[0 0 0 0]
  [0 0 0 0]
  [5 5 5 5]]

 [[0 0 0 0]
  [0 0 0 0]
  [5 5 5 5]]]


In [ ]:
arr[1, 2] = 7  # row 1, col 2 using the existing variable 'arr'
print(arr)

[[[0 0 0 0]
  [0 0 0 0]
  [5 5 5 5]]

 [[0 0 0 0]
  [0 0 0 0]
  [7 7 7 7]]]


3. Array Creation (np.ones)

In [23]:
# Creats the all array values as '1'
arr_1 = np.ones(5,)   # it also gives the datatype as 'float' by default
print(arr_1)
print(arr_1.dtype)

[1. 1. 1. 1. 1.]
float64


In [ ]:
arr_1 = np.ones(5, dtype = 'int')   # passing the datatype by Explicitly as 'int'
print(arr_1)

[1 1 1 1 1]


In [ ]:
arr_1 = np.ones(((3, 3)), dtype = int)  # 3 rows , 3 coloumns of 2D array
print(arr_1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [24]:
# Difference Between type() and dtype() with syntax
# syntax : print(type(var))  --it classifys the object or class of array
# syntax : print(arr.dtype)  --it identifies the datatype of array

In [ ]:
# Replacing the existing elements using the index values
arr_1[1, 1] = 4
print(arr_1)

[[1 1 1]
 [1 4 1]
 [1 1 1]]


In [ ]:
arr_2 = np.ones((2, 3, 4), dtype = 'int') # 2 blocks , 3 rows , 4 coloumns of 2D array
print(arr_2)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


4. Array Creation (np.full())

In [ ]:
#Creating the 1D arrays with a specific values based on the shapes 
arr2 = np.full(4, 3.14)
print(arr2)

[3.14 3.14 3.14 3.14]


In [44]:
#creating 3x3 matrix with an specific value 3.14
arr2 = np.full((3, 3), 3.14)
print(arr2)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]


In [ ]:
# Replacing the existing elements using the index values 
arr2[2, 1] = 9
print(arr2)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 9.   3.14]]


In [ ]:
#3D array 
arr = np.full((2, 3, 4), 6)
print(arr.shape) 
print(arr)

(2, 3, 4)
[[[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]]
