In [28]:
import numpy as np

1. Dimenions of Arrays
 

In [2]:
#Creating a 1D arrays (or) Normal Array creation 
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))  # type() = used to check the data type of an array

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
#Creating a 2D arrays
arr1 = np.array([[1, 2, 3],[4, 5, 6]])    #2 rows , 3 coloumns
print(arr1)
print("dimension = ",arr1.ndim)  # ndim = used check the dimensions of the array

[[1 2 3]
 [4 5 6]]
dimension =  2


In [4]:
#Creating a 3D arrays
arr2 = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])   # 3 rows , 3 coloumns
print(arr2)
print("dimension = ",arr2.ndim)  # ndim = used check the dimensions of the array

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension =  3


2. Array Creation (np.zeros())


In [5]:
# np.Zeros()
# Syntax = var = np.zeros(shape , datatype)
arr = np.zeros(5,)  # creats total 5 zeros with default datatype as 'float'

In [6]:
arr = np.zeros(5, dtype = int)  # creats total 5 zeros with a datatype as 'int' by passing Explicitly 
print(arr)

[0 0 0 0 0]


In [7]:
# creats an 3 rows , 3 coloumns with a value zeros as datatype 'int'
arr = np.zeros((3, 3), dtype = int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
# Create a 3D array of zeros (2 blocks, 3 rows, 4 cols)
arr = np.zeros((2, 3, 4), dtype = int)
print(arr) 

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [9]:
# Replacing the exixting elements using the index values 
arr[0][2] = 5   # [1]row , [5]coloumn value as 5 ,here it using the 2 blocks of matrix 
print(arr)

[[[0 0 0 0]
  [0 0 0 0]
  [5 5 5 5]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [10]:
arr[1, 2] = 7  # row 1, col 2 using the existing variable 'arr'
print(arr)

[[[0 0 0 0]
  [0 0 0 0]
  [5 5 5 5]]

 [[0 0 0 0]
  [0 0 0 0]
  [7 7 7 7]]]


3. Array Creation (np.ones)

In [11]:
# Creats the all array values as '1'
arr_1 = np.ones(5,)   # it also gives the datatype as 'float' by default
print(arr_1)
print(arr_1.dtype)

[1. 1. 1. 1. 1.]
float64


In [12]:
arr_1 = np.ones(5, dtype = 'int')   # passing the datatype by Explicitly as 'int'
print(arr_1)

[1 1 1 1 1]


In [13]:
arr_1 = np.ones(((3, 3)), dtype = int)  # 3 rows , 3 coloumns of 2D array
print(arr_1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
# Difference Between type() and dtype() with syntax
# syntax : print(type(var))  --it classifys the object or class of array
# syntax : print(arr.dtype)  --it identifies the datatype of array

In [15]:
# Replacing the existing elements using the index values
arr_1[1, 1] = 4
print(arr_1)

[[1 1 1]
 [1 4 1]
 [1 1 1]]


In [16]:
arr_2 = np.ones((2, 3, 4), dtype = 'int') # 2 blocks , 3 rows , 4 coloumns of 2D array
print(arr_2)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


4. Array Creation (np.full())

In [17]:
#Creating the 1D arrays with a specific values based on the shapes
#syntax : var = np.fill(shape, value) 
arr2 = np.full(4, 3.14)
print(arr2)

[3.14 3.14 3.14 3.14]


In [18]:
#creating 3x3 matrix with an specific value 3.14
arr2 = np.full((3, 3), 3.14)
print(arr2)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]


In [19]:
# Replacing the existing elements using the index values 
arr2[2, 1] = 9
print(arr2)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 9.   3.14]]


In [20]:
#3D array 
arr = np.full((2, 3, 4), 6)
print(arr.shape) 
print(arr)

(2, 3, 4)
[[[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]]


In [21]:
#syntax : var = var.astype(datatype) or var.astype('i') , 'i' = int
arr2[1,2] = 7
arr2 = arr2.astype('int')   # convertion of float into int using astype() function 
print(arr2)

[[3 3 3]
 [3 3 7]
 [3 9 3]]


5. Array Creation (np.arange())

In [ ]:
# Creats an array within the given range 
#Synatx : var = np.arange(start, end)
arr_3 = np.arange(0,10)
print(arr_3)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
# Creats an even arrays within the given range with step '2'
#syntax = var = np.arange(start : stop : step)
arr = np.arange(0, 21, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [24]:
# Countdown from 10 to 1 using Negetive indexing as step (-1)
arr = np.arange(10, 0, -1)
print(arr)  

[10  9  8  7  6  5  4  3  2  1]


In [25]:
# Multiples of 5 from 0 to 100
arr = np.arange(0, 101, 5)
print(arr)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


In [26]:
# Odd numbers from 1 to 19
arr = np.arange(1, 20, 2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
# Reshape into 3x3 matrix -->it only occures when it depends on the total numbers to given matrix only
arr = np.arange(1, 10).reshape((3, 3))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Floating Point Values 
arr = np.arange(1.0, 9.0)
print(arr)
# In floating point values are same as 1.0 from given 1. both are same

[1. 2. 3. 4. 5. 6. 7. 8.]


6. Array Creation (np.linespace())

In [ ]:
# Creats a array of evenly spaced values between a given 'start' and 'stop' value, based on the 'number' of elements required.
#syntx : var = np.linspace(start, stop, num)
arr = np.linspace(0, 5, 4)
print(arr)
# In linspace the 'start' and 'stop' numbers both are considered & the output always in 'Float point' by default
# Step is workes on the Formula "step = stop - start / num -1"

[0.         1.66666667 3.33333333 5.        ]


In [ ]:
arr = np.linspace(0, 6, 5)
# If we want a array in the type of 'int' us astype() function 
print(arr.astype(int))
# All the problems in linspace are works on the step formula which gives an equal spaces 

[0 1 3 4 6]


In [ ]:
# Create array with No End Point
arr = np.linspace(1, 9, 5, endpoint = False)
print(arr)
# Passing the Arguments 'endpoint = False' which removes the last element

[1.  2.6 4.2 5.8 7.4]


In [ ]:
# Creats array with End point Normal Linspace
arr = np.linspace(2, 8, 5, endpoint = True)
print(arr)
# Passing the arguments 'endpoint = False' or Without passing it , gives default

[2.  3.5 5.  6.5 8. ]


In [ ]:
# Creats an array and gives the step size were passing the argument 'retstep = True'
arr = np.linspace(2, 8, 5, retstep = True)
print(arr)
# endpoint controls whether last element is included, and retstep only returns the step size

(array([2. , 3.5, 5. , 6.5, 8. ]), np.float64(1.5))
