1. Array Attributes

In [1]:
import numpy as np

In [2]:
# After Creating the Numpy Arrays , Attributes helps to understand the structure of Array
# Determining the ndim, shape, size, dtype, nbytes, 
# Following Example on array attributes
# 1D Array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print("Dimension :",arr.ndim) # ndim --> Number of Dimensions
print("Shape :",arr.shape) #shape --> Gives the shape of the array as tuple
print("Size :", arr.size) #size --> Gives the total number of elements present in array
print("DataType :",arr.dtype) # dtype --> Classifies the datatype of array
print("Number of Bytes :",arr.nbytes) # nbytes --> Total memory used

[1 2 3 4 5]
Dimension : 1
Shape : (5,)
Size : 5
DataType : int64
Number of Bytes : 40


2. ndim --> Number of Dimension

In [3]:
# ndim Which gives the number of dimension of an array 
arr = np.array([1, 2, 3, 4, 5, 6]) # 1D Array
arr_1 = np.array([[1, 2, 3],[4, 5, 6]]) # 2D Array
arr_2 = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]]) # 3D Array

# Function
def array_attributes(ar):
    print("Array:\n", ar)
    print("Dimensions:", ar.ndim)
    print("Shape:", ar.shape)
    print("Size:", ar.size)
    print("-" * 30)

# Function calls
array_attributes(arr)
array_attributes(arr_1)
array_attributes(arr_2)

Array:
 [1 2 3 4 5 6]
Dimensions: 1
Shape: (6,)
Size: 6
------------------------------
Array:
 [[1 2 3]
 [4 5 6]]
Dimensions: 2
Shape: (2, 3)
Size: 6
------------------------------
Array:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimensions: 3
Shape: (1, 3, 3)
Size: 9
------------------------------


In [4]:
# 'def' is used to create your own function (a reusable block of code) used in several codes, Here I mentioned because I used it 
# syntax : def function_name(parameters):
                # work
            #return result
item = np.array([1, 2, 3])
def array_attributes(arr):
    print(arr.ndim)
array_attributes(item)

1


In [5]:
# using the array creation fuction 
arr = np.zeros((2, 3)).astype('i4') # Data type into 'int' --> 'i4' using astype
arr_1 = np.ones((2, 3)).astype('i4')
arr_2 = np.full((2, 3), 23).astype('i4')
listes = [arr, arr_1, arr_2] # Here the created an variable listes to store the array varibles to use in for loop
def array(items):
    print(items)
    print(items.ndim)
    print("-"*40)
# using a for loop because instead of repeating multiple times of fuctions names 
for i in listes: 
    array(i)

[[0 0 0]
 [0 0 0]]
2
----------------------------------------
[[1 1 1]
 [1 1 1]]
2
----------------------------------------
[[23 23 23]
 [23 23 23]]
2
----------------------------------------


3. shape() --> Find the shape of the arrays

In [9]:
a = np.array([1, 2, 3, 4]) # 1D Array
b = np.array([[1, 2], [3, 4]]) # 2D Array
c = np.array([[[1], [2]], [[3], [4]]]) # 3D Array
d = [a, b, c]
def array_shapes(items):
    print("Shapes :", items.shape)
    print("-"*40)
for i in d:
    array_shapes(i)

Shapes : (4,)
----------------------------------------
Shapes : (2, 2)
----------------------------------------
Shapes : (2, 2, 1)
----------------------------------------


In [12]:
# Create a 2×3 array filled with zeros 
# problems using the array creation functions
arr = np.zeros((2, 3))
print(arr)
print("-"*20)
print(arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
--------------------
(2, 3)


In [11]:
# Create a 3×3 array filled with 7
arr = np.full((3, 3), 7)
print(arr)
print("-"*20)
print(arr.shape)

[[7 7 7]
 [7 7 7]
 [7 7 7]]
--------------------
(3, 3)


In [13]:
# Create a 4×2 array of ones
arr = np.ones((4, 2))
print(arr)
print("-"*20)
print(arr.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
--------------------
(4, 2)


In [ ]:
# Problems on ndim + shape 
np.random.seed(1) # reproducability
a = np.array([1, 2, 4, 5, 6])
b = np.random.normal(0, 1, (3, 4)).astype(int)
c = np.random.randint(0, 10, (3, 4))
d = [a, b, c]
def array_attributes(items):
    print(items)
    print("shapes :",items.shape)
    print("Dimensions :", items.ndim)
    print("-"*30)
for i in d:
    array_attributes(i)


[1 2 4 5 6]
shapes : (5,)
Dimensions : 1
------------------------------
[[ 1  0  0 -1]
 [ 0 -2  1  0]
 [ 0  0  1 -2]]
shapes : (3, 4)
Dimensions : 2
------------------------------
[[7 0 6 9]
 [9 7 6 9]
 [1 0 1 8]]
shapes : (3, 4)
Dimensions : 2
------------------------------


In [27]:
a = np.arange(1, 7)
b = a.reshape((2, 3))
print(b)

[[1 2 3]
 [4 5 6]]
