1. Array Attributes

In [3]:
import numpy as np

In [ ]:
# After Creating the Numpy Arrays , Attributes helps to understand the structure of Array
# Determining the ndim, shape, size, dtype, nbytes, 
# Following Example on array attributes
# 1D Array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print("Dimension :",arr.ndim) # ndim --> Number of Dimensions
print("Shape :",arr.shape) #shape --> Gives the shape of the array as tuple
print("Size :", arr.size) #size --> Gives the total number of elements present in array
print("DataType :",arr.dtype) # dtype --> Classifies the datatype of array
print("Number of Bytes :",arr.nbytes) # nbytes --> Total memory used

[1 2 3 4 5]
Dimension : 1
Shape : (5,)
Size : 5
DataType : int64
Number of Bytes : 40


2. ndim --> Number of Dimension

In [8]:
# ndim Which gives the number of dimension of an array 
arr = np.array([1, 2, 3, 4, 5, 6]) # 1D Array
arr_1 = np.array([[1, 2, 3],[4, 5, 6]]) # 2D Array
arr_2 = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]]) # 3D Array

# Function
def array_attributes(ar):
    print("Array:\n", ar)
    print("Dimensions:", ar.ndim)
    print("Shape:", ar.shape)
    print("Size:", ar.size)
    print("-" * 30)

# Function calls
array_attributes(arr)
array_attributes(arr_1)
array_attributes(arr_2)

Array:
 [1 2 3 4 5 6]
Dimensions: 1
Shape: (6,)
Size: 6
------------------------------
Array:
 [[1 2 3]
 [4 5 6]]
Dimensions: 2
Shape: (2, 3)
Size: 6
------------------------------
Array:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimensions: 3
Shape: (1, 3, 3)
Size: 9
------------------------------


In [9]:
# 'def' is used to create your own function (a reusable block of code) used in several codes, Here I mentioned because I used it 
# syntax : def function_name(parameters):
                # work
            #return result
item = np.array([1, 2, 3])
def array_attributes(arr):
    print(arr.ndim)
array_attributes(item)

1


In [ ]:
# using the array creation fuction 
arr = np.zeros((2, 3)).astype('i4') # Data type into 'int' --> 'i4' using astype
arr_1 = np.ones((2, 3)).astype('i4')
arr_2 = np.full((2, 3), 23).astype('i4')
listes = [arr, arr_1, arr_2] # Here the created an variable listes to store the array varibles to use in for loop
def array(items):
    print(items)
    print(items.ndim)
    print("-"*40)
# using a for loop because instead of repeating multiple times of fuctions names 
for i in listes: 
    array(i)

[[0 0 0]
 [0 0 0]]
2
----------------------------------------
[[1 1 1]
 [1 1 1]]
2
----------------------------------------
[[23 23 23]
 [23 23 23]]
2
----------------------------------------
